image: node:alpine

setup-deps-and-sls: &setup-deps-and-sls |-
  npm ci --legacy-peer-deps
  npm i serverless@3.23.0 -g
  serverless config credentials --provider aws --key ${AWS_LAMBDA_KEY} --secret ${AWS_LAMBDA_SECRET}

definitions:
  steps:
    - step: &compile
        name: Compile
        caches:
          - node
        script:
          - npm install --legacy-peer-deps
          - npm run lint
          - npm run test
    - step: &deploy-example
        name: Deploy example service
        trigger: manual
        caches:
          - node
        script:
          - *setup-deps-and-sls
          - ./node_modules/.bin/serverless example:deploy --stage ${STAGE}
          - ./node_modules/.bin/serverless migration:invoke --stage ${STAGE} --function migrations
    - step: &deploy-migration
        name: Deploy migration service
        trigger: manual
        caches:
          - node
        script:
          - *setup-deps-and-sls
          - ./node_modules/.bin/serverless migration:deploy --stage ${STAGE}
          - ./node_modules/.bin/serverless migration:invoke --stage ${STAGE} --function migrations
    - step: &deploy-all
        name: Deploy all services
        trigger: manual
        # size: 2x # might be necessary at some point
        caches:
          - node
        script:
          - *setup-deps-and-sls
          - ./node_modules/.bin/serverless deploy --stage ${STAGE}
          - ./node_modules/.bin/serverless migration:invoke --stage ${STAGE} --function migrations

pipelines:
  default:
    - step: *compile
  custom:
    deploy-example-to-dev:
      - step: *compile
      - step:
          <<: *deploy-example
          deployment: dev
          name: Deploy example service to dev
    deploy-migration-to-dev:
      - step: *compile
      - step:
          <<: *deploy-migration
          deployment: dev
          name: Deploy migration service to dev
    deploy-all-to-dev:
      - step: *compile
      - step:
          <<: *deploy-all
          deployment: dev
          name: Deploy all services to dev
    deploy-example-to-production:
      - step: *compile
      - step:
          <<: *deploy-example
          deployment: production
          name: Deploy example service to production
    deploy-migration-to-production:
      - step: *compile
      - step:
          <<: *deploy-migration
          deployment: production
          name: Deploy migration service to production
    deploy-all-to-production:
      - step: *compile
      - step:
          <<: *deploy-all
          deployment: production
          name: Deploy all services to production
